// Solid-Calculator-SolidJS/src/App.jsx
import { createSignal, For } from "solid-js";
import Button from "./components/Button";

function App() {
  const [value, setValue] = createSignal('');

  const buttonRows = [
    ["9", "8", "7", "*"],
    ["6", "5", "4", "+"],
    ["3", "2", "1", "−"],
    ["0", ".", "=", "÷"],
  ];

  return (
    <main class="flex justify-center items-center w-screen h-screen bg-gradient-to-br from-gray-900 via-blue-900 to-black">
      <div class="w-96 h-[28rem] bg-gradient-to-b from-blue-700 to-blue-900 rounded-2xl shadow-2xl p-6 flex flex-col items-center border border-blue-400/30">
        
        {/* Display */}
        <header class="w-full mb-6">
          <input
            type="text"
            readOnly
            value={value()}
            class="w-full h-14 px-4 text-right text-2xl font-mono rounded-lg bg-gray-100 shadow-inner focus:outline-none border border-gray-300"
          />
        </header>

        {/* Buttons */}
        <section class="w-full flex flex-col gap-4 justify-center items-center">
          <For each={buttonRows}>
            {(row) => (
              <div class="flex justify-evenly w-full gap-4">
                <For each={row}>
                  {(command) => (
                    <Button
                      value={value}
                      setValue={setValue}
                      command={command}
                      class="flex-1 h-14 rounded-xl bg-gradient-to-b from-blue-500 to-blue-600 text-white text-xl font-semibold shadow-md hover:from-blue-400 hover:to-blue-500 active:scale-95 transition-transform duration-150"
                    />
                  )}
                </For>
              </div>
            )}
          </For>

          {/* Clear Button */}
          <button
            class="w-full h-14 mt-2 rounded-xl bg-gradient-to-b from-red-600 to-red-700 text-white text-xl cursor-pointer font-bold shadow-md hover:from-red-500 hover:to-red-600 active:scale-95 transition-transform duration-150"
            onClick={() => setValue("")}
          >
            Clear
          </button>
        </section>
      </div>
    </main>
  );
}

export default App;

// Number-Guess-Game/src/App.jsx
import { useState } from 'react';

function App() {
  const [random, setRandom] = useState(null);
  const [response, setResponse] = useState("");
  const [value, setValue] = useState("");
  const [attempts, setAttempts] = useState(0);
  const [win, setWin] = useState(false);

  const handleClick = () => {
    setRandom(Math.floor(Math.random() * 101));
    setResponse("Number has been generated! Start guessing...");
    setValue("");
    setAttempts(0);
  };

  const handleChange = (e) => {
    setValue(e.target.value);
    if (attempts == 10) {
      setResponse(`⚠️ Limit Reached, Sorry, The number was ${random}!`);
      setAttempts(0);
      setRandom(null);
      setValue("");
      return;
    }
  };

  const handleSubmit = () => {
    if (random === null) {
      setResponse("⚠️ Please generate a number first!");
      return;
    }
    if (value === "") {
      setResponse("⚠️ Please enter a number!");
      return;
    }


    const guess = Number(value);
    setAttempts((prev) => prev + 1);

    if (guess === random) {
      setWin(true);
      setResponse(`🎉 You WON in ${attempts + 1} attempts! The number was ${random}`);
    } else if (guess > random) {
      setResponse("📉 Too large, try a smaller number!");
    } else {
      setResponse("📈 Too small, try a bigger number!");
    }
  };

  return (
    <div className="w-screen h-screen flex justify-center items-center bg-gradient-to-r from-purple-700 via-pink-600 to-red-500">
      <div className="w-96 h-[500px] flex flex-col items-center rounded-3xl shadow-2xl p-6 justify-around bg-white">
        <h1 className="text-3xl font-extrabold text-purple-700">Number Guess Game</h1>

        <div className="w-full flex flex-col items-center gap-4">
          <input
            type="number"
            className="bg-gray-800 rounded-xl border border-gray-400 h-12 w-3/4 text-center text-lg focus:outline-none focus:ring-2 text-white focus:ring-purple-500"
            onChange={handleChange}
            value={value}
          />
          <button
            className="bg-green-600 w-3/4 h-12 rounded-xl text-white text-lg font-semibold cursor-pointer hover:bg-green-500 transition"
            onClick={handleSubmit}
          >
            Submit Guess
          </button>
          <button
            className="bg-blue-600 w-3/4 h-12 rounded-xl text-white text-lg font-semibold cursor-pointer hover:bg-blue-500 transition"
            onClick={handleClick}
          >
            Generate Number
          </button>
        </div>

        <h2 className={`font-bold text-lg text-center mt-4 ${win ? 'text-green-500': 'text-amber-400'}`}>{response}</h2>
        {attempts > 0 && random !== null && (
          <p className="text-sm text-gray-600">Attempts: {attempts}</p>
        )}
      </div>
    </div>
  );
}

export default App;
