// Solid-Calculator-SolidJS/src/App.jsx
import { createSignal, For } from "solid-js";
import Button from "./components/Button";

function App() {
  const [value, setValue] = createSignal('');

  const buttonRows = [
    ["9", "8", "7", "*"],
    ["6", "5", "4", "+"],
    ["3", "2", "1", "−"],
    ["0", ".", "=", "÷"],
  ];

  return (
    <main class="flex justify-center items-center w-screen h-screen bg-gradient-to-br from-gray-900 via-blue-900 to-black">
      <div class="w-96 h-[28rem] bg-gradient-to-b from-blue-700 to-blue-900 rounded-2xl shadow-2xl p-6 flex flex-col items-center border border-blue-400/30">
        
        {/* Display */}
        <header class="w-full mb-6">
          <input
            type="text"
            readOnly
            value={value()}
            class="w-full h-14 px-4 text-right text-2xl font-mono rounded-lg bg-gray-100 shadow-inner focus:outline-none border border-gray-300"
          />
        </header>

        {/* Buttons */}
        <section class="w-full flex flex-col gap-4 justify-center items-center">
          <For each={buttonRows}>
            {(row) => (
              <div class="flex justify-evenly w-full gap-4">
                <For each={row}>
                  {(command) => (
                    <Button
                      value={value}
                      setValue={setValue}
                      command={command}
                      class="flex-1 h-14 rounded-xl bg-gradient-to-b from-blue-500 to-blue-600 text-white text-xl font-semibold shadow-md hover:from-blue-400 hover:to-blue-500 active:scale-95 transition-transform duration-150"
                    />
                  )}
                </For>
              </div>
            )}
          </For>

          {/* Clear Button */}
          <button
            class="w-full h-14 mt-2 rounded-xl bg-gradient-to-b from-red-600 to-red-700 text-white text-xl cursor-pointer font-bold shadow-md hover:from-red-500 hover:to-red-600 active:scale-95 transition-transform duration-150"
            onClick={() => setValue("")}
          >
            Clear
          </button>
        </section>
      </div>
    </main>
  );
}

export default App;

// Calculator-React/src/App.jsx
import React, { useRef, useState } from 'react'
import Button from './components/Button'

const App = () => {
  const [value, setValue] = useState("");
  const input = useRef();

  const handleChange = (amount) => {
    setValue(prev => prev + amount); // append instead of replace
  }

  const handleClear = () => {
    setValue("");
  }

  const handleEvaluate = () => {
    try {
      setValue(eval(value).toString()); // evaluate expression
    } catch {
      setValue("Error");
      input.current.style.color = "red";
      setTimeout(function() {
        setValue("");
      }, 2000);
    }
  }

  let row1 = ["1", "2", "3", "*"];
  let row2 = ["4", "5", "6", "+"];
  let row3 = ["7", "8", "9", "-"];
  let row4 = ["0", ".", "%", "/"];

  return (
    <div className='w-screen h-screen flex justify-center items-center bg-gradient-to-br from-gray-900 to-gray-700'>
      <div className='h-2/3 w-1/4 bg-black rounded-3xl flex flex-col items-center justify-around shadow-2xl shadow-blue-800'>
        <div className='w-full h-12 text-white font-bold text-3xl flex justify-center items-center drop-shadow-lg'>
          Calculator
        </div>
        <div className='w-full h-3/4 p-3 justify-around'>
          <div className='flex justify-around h-10'>
            <input 
              type="text" 
              className='w-2/3 h-10 bg-gray-700 rounded-2xl text-black pl-3 font-bold text-gray-200 shadow-inner focus:outline-none focus:ring-2 focus:ring-yellow-400 transition-all duration-200' 
              value={value} 
              ref={input}
              readOnly
            />
            <button 
              className='w-1/4 bg-green-500 h-10 rounded-3xl font-bold cursor-pointer shadow-md hover:bg-red-800 transition-all shadow-green-700 duration-200' 
              onClick={handleClear}
            >
              Clear
            </button>
          </div>
          <div className='flex flex-col justify-around h-4/5 my-3'>
            <Button props={row1} handler={handleChange}/>
            <Button props={row2} handler={handleChange}/>
            <Button props={row3} handler={handleChange}/>
            <Button props={row4} handler={handleChange}/>
            <div className='flex justify-center mt-3'>
              <button 
                className='font-bold text-xl w-24 h-10 text-black bg-yellow-400 rounded-xl cursor-pointer shadow-md shadow-amber-100 hover:bg-yellow-500 transition-all duration-200 hover:text-white' 
                onClick={handleEvaluate}
              >
                =
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default App
